{% set name = "Farabio" %}
{% set version = "2.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://files.pythonhosted.org/packages/5e/0c/4a007dba208d09bb3a1693b7e80c0c2be21b880f733a9316980ac0185f34/farabio-2.0.0.tar.gz
  sha256: ee597e1abb1a4f96e3ac549802416127b56f08b51078707da23567def180c305

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - farabio

about:
  home: https://github.com/tuttelikz/farabio
  license: GPL-3.0-only
  license_family: GPL3
  summary: Python toolkit for AI-based biomedical image analysis